language: php

php:
  - 7.4

stages:
  - Composer install
  - Run tests

jobs:
  include:
    - stage: Composer install
      script: composer install
    - stage: Run Tests
      script: composer run-script test
