language: php

php:
  - 7.4

stages:
  - composer install
  - tests

jobs:
  include:
    - stage: composer install
      script: composer install
    - stage: tests
      script: composer run-script test
